name: codestyle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: typecheck:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Check Type Safety
        run: uv run pyright

  codestyle:
    name: codestyle:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Check Code Style
        run: uv run ruff check

      - name: Format Code
        run: uv run ruff format --check
