name: Tests

on:
  pull_request:

jobs:
  test:
    name: test:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Run tests
        run: uv run pytest tests/

